FROM ubuntu:wily

ENV DNSMASQ_VERSION 2.75-1
ENV GIT_VERSION 1:2.5.0-1

RUN apt-get update && \
    apt-get install -y \
    dnsmasq=${DNSMASQ_VERSION} \
    git=${GIT_VERSION} && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /opt/mayu
WORKDIR /opt/mayu

RUN if [ ! -f config.yaml ]; then cp config.yaml.dist config.yaml; fi

ENTRYPOINT ["./mayu", "-config=config.yaml"]
CMD ["-v=12"]
