version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: mayu
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: architect
          name: push-to-quay
          image: "quay.io/giantswarm/mayu"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/