#!/bin/sh

ETCD_VERSION=v2.2.5-gs-1
FLEET_VERSION=v0.11.5-gs-grpc-1
DOCKER_VERSION=1.10.3
YOCHU_VERSION=0.19.1
RKT_VERSION=v1.2.0
K8S_VERSION=v1.2.0

mkdir -p ./yochu

if [ ! -d "./yochu/yochu/${YOCHU_VERSION}" ]; then
	mkdir -p ./yochu/yochu/${YOCHU_VERSION}
	wget -O ./yochu/yochu/${YOCHU_VERSION}/yochu https://downloads.giantswarm.io/yochu/${YOCHU_VERSION}/yochu
fi

if [ ! -d "./yochu/etcd/${ETCD_VERSION}" ]; then
	mkdir -p ./yochu/etcd/${ETCD_VERSION}
	wget -O ./yochu/etcd/${ETCD_VERSION}/etcd https://downloads.giantswarm.io/etcd/${ETCD_VERSION}/etcd
	wget -O ./yochu/etcd/${ETCD_VERSION}/etcdctl https://downloads.giantswarm.io/etcd/${ETCD_VERSION}/etcdctl
fi

if [ ! -d "./yochu/fleet/${FLEET_VERSION}" ]; then
	mkdir -p ./yochu/fleet/${FLEET_VERSION}
	wget -O ./yochu/fleet/${FLEET_VERSION}/fleetd https://downloads.giantswarm.io/fleet/${FLEET_VERSION}/fleetd
	wget -O ./yochu/fleet/${FLEET_VERSION}/fleetctl https://downloads.giantswarm.io/fleet/${FLEET_VERSION}/fleetctl
fi

if [ ! -d "./yochu/docker/${DOCKER_VERSION}" ]; then
	mkdir -p ./yochu/docker/${DOCKER_VERSION}
	wget -O ./yochu/docker/${DOCKER_VERSION}/docker https://downloads.giantswarm.io/docker/${DOCKER_VERSION}/docker
fi

if [ ! -d "./yochu/rkt/${RKT_VERSION}" ]; then
	mkdir -p ./yochu/rkt/${RKT_VERSION}
	wget -O ./yochu/rkt/${RKT_VERSION}/rkt https://downloads.giantswarm.io/rkt/${RKT_VERSION}/rkt
fi

if [ ! -d "./yochu/k8s/${K8S_VERSION}" ]; then
	mkdir -p ./yochu/k8s/${K8S_VERSION}
	wget -O ./yochu/k8s/${K8S_VERSION}/kubectl https://downloads.giantswarm.io/k8s/${K8S_VERSION}/kubectl
fi
