#!/bin/sh

set -eu

: ${1?"Usage: $0 <flatcar-version>"}

FLATCAR_VERSION=$1
FLATCAR_CHANNEL=${2:-stable}
IMAGE_PATH=$(pwd)/images/qemu/${FLATCAR_VERSION}
KERNEL=flatcar_production_qemu.vmlinuz
USRFS=flatcar_production_qemu_usr_image.squashfs

mkdir -p ${IMAGE_PATH}
cd ${IMAGE_PATH}

# remove old images
rm -f coreos*

wget http://${FLATCAR_CHANNEL}.release.flatcar-linux.net/amd64-usr/${FLATCAR_VERSION}/flatcar_production_pxe.vmlinuz
wget http://${FLATCAR_CHANNEL}.release.flatcar-linux.net/amd64-usr/${FLATCAR_VERSION}/flatcar_production_pxe.vmlinuz.sig
wget http://${FLATCAR_CHANNEL}.release.flatcar-linux.net/amd64-usr/${FLATCAR_VERSION}/flatcar_production_pxe_image.cpio.gz
wget http://${FLATCAR_CHANNEL}.release.flatcar-linux.net/amd64-usr/${FLATCAR_VERSION}/flatcar_production_pxe_image.cpio.gz.sig
echo "$FLATCAR_VERSION" > flatcar-version

gpg --verify flatcar_production_pxe.vmlinuz.sig
gpg --verify flatcar_production_pxe_image.cpio.gz.sig

docker run --rm -v $IMAGE_PATH:/usr/code/images --net=host ubuntu:xenial /bin/bash -c "apt-get update -y && apt-get install cpio && \
      zcat /usr/code/images/flatcar_production_pxe_image.cpio.gz | cpio -i --quiet --sparse usr.squashfs && mv usr.squashfs /usr/code/images/$USRFS"

cp flatcar_production_pxe.vmlinuz $KERNEL

sha256sum $KERNEL > $KERNEL.sha256
sha256sum $USRFS > $USRFS.sha256

cd -
