#!/bin/sh

ETCD_VERSION=v2.2.5-gs-1
FLEET_VERSION=v0.11.3-gs-2
DOCKER_VERSION=1.6.2
YOCHU_VERSION=0.18.0

mkdir -p ./assets

if [ ! -d "./assets/yochu/${YOCHU_VERSION}" ]; then
	mkdir -p ./assets/yochu/${YOCHU_VERSION}
	wget -O ./assets/yochu/${YOCHU_VERSION}/yochu https://downloads.giantswarm.io/yochu/${YOCHU_VERSION}/yochu
fi

if [ ! -d "./assets/etcd/${ETCD_VERSION}" ]; then
	mkdir -p ./assets/etcd/${ETCD_VERSION}
	wget -O ./assets/etcd/${ETCD_VERSION}/etcd https://downloads.giantswarm.io/etcd/${ETCD_VERSION}/etcd
	wget -O ./assets/etcd/${ETCD_VERSION}/etcdctl https://downloads.giantswarm.io/etcd/${ETCD_VERSION}/etcdctl
fi

if [ ! -d "./assets/fleet/${FLEET_VERSION}" ]; then
	mkdir -p ./assets/fleet/${FLEET_VERSION}
	wget -O ./assets/fleet/${FLEET_VERSION}/fleetd https://downloads.giantswarm.io/fleet/${FLEET_VERSION}/fleetd
	wget -O ./assets/fleet/${FLEET_VERSION}/fleetctl https://downloads.giantswarm.io/fleet/${FLEET_VERSION}/fleetctl
fi

if [ ! -d "./assets/docker/${DOCKER_VERSION}" ]; then
	mkdir -p ./assets/docker/${DOCKER_VERSION}
	wget -O ./assets/docker/${DOCKER_VERSION}/docker https://downloads.giantswarm.io/docker/${DOCKER_VERSION}/docker
fi
